<?php

namespace Plugin\membership\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\membership\Entity\MbOption;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * MbOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MbOptionRepository extends AbstractRepository
{
    /**
     * MbOptionRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, MbOption::class);
    }

    /**
     * @param int $id
     *
     * @return null|Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
